### ISSUE TITLE
Lack of Unit Test Execution in GitHub Actions Runner for Pull Request (PR) Creation

### ISSUE THREAD

**Issue by levimoore1992** [Govexec/django-formulaic#42]
The GitHub Actions runner configured for the repository does not execute unit tests when a new pull request is created. Unit tests play a critical role in ensuring the correctness and stability of the codebase, especially during the review process of pull requests. By not running unit tests automatically upon PR creation, the repository's quality and reliability may be compromised, and issues or regressions could go unnoticed until later stages of development or deployment.

**Comment by jennifere** [comment]
Sounds an awful lot like this was generated by ChatGPT.
