### ISSUE TITLE
Upgrade Node.js version to the latest LTS for improved compatibility and support

### ISSUE THREAD

**Issue by levimoore1992** [Govexec/django-formulaic#43]
I would like to propose upgrading the Node.js version used in our Ember application from version 7.x to the latest LTS (Long-Term Support) version. This upgrade is necessary to address several important factors and ensure the long-term viability and maintainability of our application.

Reasons for upgrading the Node.js version:

Compatibility: Node.js version 7.x is significantly outdated and no longer receives active maintenance or support from the Node.js community. By upgrading to the latest LTS version, we align ourselves with the current ecosystem and ensure compatibility with the latest tools, packages, and frameworks.

Security: Using an outdated Node.js version poses security risks as vulnerabilities discovered in older versions may remain unpatched. Upgrading to the latest LTS version ensures that our application benefits from the latest security patches and fixes, mitigating potential risks and enhancing overall security.

Performance and Stability: Newer versions of Node.js often introduce performance improvements and stability enhancements. By upgrading, we can take advantage of these optimizations, resulting in a more efficient and reliable application.

Ecosystem Support: The Node.js community primarily focuses on providing support, bug fixes, and updates for the LTS versions. By upgrading to the latest LTS version, we gain access to a vibrant ecosystem of libraries, tools, and resources actively maintained and updated by the community.

Ember CLI Compatibility: Ember CLI, the command-line interface for managing Ember.js applications, is more likely to provide seamless integration and compatibility with the latest LTS version of Node.js. This ensures a smoother development experience and reduces the likelihood of encountering compatibility issues between Ember CLI and our Node.js environment.

**Comment by jennifere** [comment]
More ChatGPT rambling.
